# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Cypress Tests
on:
  push:
    branches: [ main ]
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cypress run
      uses: cypress-io/github-action@v2  
    - name: Cypress tests
      uses: ./
      with: 
          working-directory: ./
          install-command: npm install
          build: npm run build
          start: npm start      
          browser: chrome
          wait-on: 'http://localhost:4200'
          config: baseUrl=http://localhost:4200

        

 
